name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: true
        matrix:
            platform:
                - html5
    steps:
      - uses: actions/checkout@v4
      - uses: chickensoft-games/setup-godot@v2.2.0
        with:
          version: 4.3.0
          include-templates: true
          use-dotnet: false
      - name: Web Build
        run: |
          echo "Running Godot import and capturing output..."
          godot --headless --import --path . 2>&1 | tee godot_output.log
          echo "Checking Godot output for errors..."
          if grep -q "Parse error" godot_output.log; then
              echo "ERROR: Godot build failed due to a Parse error in script."
              exit 1
          fi
          if grep -q "ERROR: Failed to load script" godot_output.log; then
              echo "ERROR: Godot build failed due to script loading error."
              exit 1
          fi
          mkdir -p build/${{ matrix.platform }}
          godot -v --export-release "${{ matrix.platform }}" build/${{ matrix.platform }}/index.html --headless

      - name: "Show Results"
        run: |
          sudo apt-get install tree
          tree build
      
      # Upload to itch.io
      - name: Upload to itch.io project
        uses: robpc/itchio-upload-action@v1
        with:
          path: build/${{ matrix.platform }}
          project: gongbaodd/landlord-simulator
          channel: html5
          api-key: ${{ secrets.ITCHIO_API_KEY }}

      # Output
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build/${{ matrix.platform }}

      # Send Notification
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "✅ The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed.\n Commit message: ${{ github.event.head_commit.message }}\n repository URL: ${{ github.event.repository.url }}\n website URL: https://gongbaodd.itch.io/landlord-simulator"